"""create_initial_tables

Revision ID: 4adbf720aa5d
Revises: b3616dce5de0
Create Date: 2026-02-04 22:45:05.508315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4adbf720aa5d'
down_revision = 'b3616dce5de0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('account_type', sa.Enum('credit', 'debit', 'bank', 'cash', 'other', name='accounttype'), nullable=False),
    sa.Column('learned_format_id', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['learned_format_id'], ['learned_formats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alert_settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('large_purchase_threshold', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('large_purchase_multiplier', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('unusual_merchant_threshold', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('subscription_review_days', sa.Integer(), nullable=False),
    sa.Column('last_subscription_review', sa.DateTime(), nullable=True),
    sa.Column('annual_charge_warning_days', sa.Integer(), nullable=False),
    sa.Column('alerts_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('learned_formats',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('file_type', sa.Enum('csv', 'ofx', 'qfx', name='filetype'), nullable=False),
    sa.Column('column_mapping', sa.JSON(), nullable=False),
    sa.Column('date_format', sa.String(length=50), nullable=False),
    sa.Column('amount_style', sa.Enum('signed', 'separate_columns', 'parentheses_negative', name='amountstyle'), nullable=False),
    sa.Column('debit_column', sa.Integer(), nullable=True),
    sa.Column('credit_column', sa.Integer(), nullable=True),
    sa.Column('skip_rows', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learned_formats_fingerprint'), 'learned_formats', ['fingerprint'], unique=False)
    op.create_table('import_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', name='importstatus'), nullable=False),
    sa.Column('transactions_imported', sa.Integer(), nullable=False),
    sa.Column('transactions_skipped', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recurring_groups',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('merchant_pattern', sa.String(length=255), nullable=False),
    sa.Column('expected_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('amount_variance', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('frequency', sa.Enum('weekly', 'biweekly', 'monthly', 'quarterly', 'yearly', name='frequency'), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=True),
    sa.Column('last_seen_date', sa.Date(), nullable=True),
    sa.Column('next_expected_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_corrections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('raw_description', sa.Text(), nullable=False),
    sa.Column('clean_merchant', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('raw_description', sa.Text(), nullable=False),
    sa.Column('clean_merchant', sa.String(length=255), nullable=True),
    sa.Column('category_id', sa.String(length=36), nullable=True),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('recurring_group_id', sa.String(length=36), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('ai_categorized', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['recurring_group_id'], ['recurring_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_transaction_category', 'transactions', ['category_id'], unique=False)
    op.create_index('idx_transaction_date_account', 'transactions', ['date', 'account_id'], unique=False)
    op.create_index(op.f('ix_transactions_date'), 'transactions', ['date'], unique=False)
    op.create_index(op.f('ix_transactions_hash'), 'transactions', ['hash'], unique=True)
    op.create_table('alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('large_purchase', 'price_increase', 'new_recurring', 'subscription_review', 'unusual_merchant', 'annual_charge', name='alerttype'), nullable=False),
    sa.Column('severity', sa.Enum('info', 'warning', 'attention', name='severity'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('transaction_id', sa.String(length=36), nullable=True),
    sa.Column('recurring_group_id', sa.String(length=36), nullable=True),
    sa.Column('alert_metadata', sa.JSON(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('is_dismissed', sa.Boolean(), nullable=False),
    sa.Column('action_taken', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recurring_group_id'], ['recurring_groups.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_alerts_is_read'), 'alerts', ['is_read'], unique=False)
    op.create_index(op.f('ix_alerts_type'), 'alerts', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerts_type'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_is_read'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_transactions_hash'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_date'), table_name='transactions')
    op.drop_index('idx_transaction_date_account', table_name='transactions')
    op.drop_index('idx_transaction_category', table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('user_corrections')
    op.drop_table('recurring_groups')
    op.drop_table('import_logs')
    op.drop_index(op.f('ix_learned_formats_fingerprint'), table_name='learned_formats')
    op.drop_table('learned_formats')
    op.drop_table('categories')
    op.drop_table('alert_settings')
    op.drop_table('accounts')
    # ### end Alembic commands ###
