"""add budget alert settings

Revision ID: 5f8e67fe73f1
Revises: de69f80b660b
Create Date: 2026-02-04 23:03:16.853521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f8e67fe73f1'
down_revision = 'de69f80b660b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert_settings', sa.Column('budget_warning_threshold', sa.Integer(), nullable=False))
    op.add_column('alert_settings', sa.Column('budget_alerts_enabled', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alert_settings', 'budget_alerts_enabled')
    op.drop_column('alert_settings', 'budget_warning_threshold')
    # ### end Alembic commands ###
