"""add balance fields to account

Revision ID: 6a9f1b2c3d4e
Revises: 5f8e67fe73f1
Create Date: 2026-02-04 23:21:15.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '6a9f1b2c3d4e'
down_revision = '5f8e67fe73f1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('current_balance', postgresql.NUMERIC(12, 2), nullable=False, server_default='0.00'))
    op.add_column('accounts', sa.Column('balance_updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'balance_updated_at')
    op.drop_column('accounts', 'current_balance')
    # ### end Alembic commands ###
