"""add privacy and token map tables

Revision ID: 78d46ada1d60
Revises:
Create Date: 2026-01-10 03:11:01.732350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78d46ada1d60'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create new tables
    op.create_table('date_shifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shift_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('privacy_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('obfuscation_enabled', sa.Boolean(), nullable=False),
    sa.Column('ollama_obfuscation', sa.Boolean(), nullable=False),
    sa.Column('openrouter_obfuscation', sa.Boolean(), nullable=False),
    sa.Column('anthropic_obfuscation', sa.Boolean(), nullable=False),
    sa.Column('openai_obfuscation', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('token_maps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_type', sa.Enum('merchant', 'account', 'person', name='tokentype'), nullable=False),
    sa.Column('original_value', sa.String(length=500), nullable=False),
    sa.Column('normalized_value', sa.String(length=500), nullable=False),
    sa.Column('token', sa.String(length=50), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )

    op.create_index(op.f('ix_token_maps_id'), 'token_maps', ['id'], unique=False)
    op.create_index(op.f('ix_token_maps_normalized_value'), 'token_maps', ['normalized_value'], unique=False)
    op.create_index(op.f('ix_token_maps_token'), 'token_maps', ['token'], unique=True)
    op.create_index(op.f('ix_token_maps_token_type'), 'token_maps', ['token_type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f('ix_token_maps_token_type'), table_name='token_maps')
    op.drop_index(op.f('ix_token_maps_token'), table_name='token_maps')
    op.drop_index(op.f('ix_token_maps_normalized_value'), table_name='token_maps')
    op.drop_index(op.f('ix_token_maps_id'), table_name='token_maps')
    op.drop_table('token_maps')
    op.drop_table('privacy_settings')
    op.drop_table('date_shifts')
    # ### end Alembic commands ###
