"""add budget alert types and budget_id field

Revision ID: de69f80b660b
Revises: 4adbf720aa5d
Create Date: 2026-02-04 22:56:18.367851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de69f80b660b'
down_revision = '4adbf720aa5d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('budget_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key('fk_alerts_budget_id', 'budgets', ['budget_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_alerts_budget_id', type_='foreignkey')
        batch_op.drop_column('budget_id')
    # ### end Alembic commands ###
